repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length", "88"]
        exclude: ^(tests/|docs/|examples/)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "88"]
        language_version: python3.11
        exclude: ^(tests/|docs/|examples/)

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language_version: python3.11
        args: [
          "--max-line-length", "88",
          "--extend-ignore", "F401,E501,F821,F841,F541,W293,F811,E203",
          "--exclude", "tests/*,docs/*,examples/*"
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        language_version: python3.11
        args: ["-ll", "-i"]
        exclude: ^(tests/|docs/|examples/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        language_version: python3.11
        additional_dependencies:
          - types-aiofiles
          - types-PyYAML
          - types-Markdown
          - types-Pillow
          - types-tqdm
          - types-psutil
          - types-beautifulsoup4
          - types-requests
          - pandas-stubs
          - types-jinja2
          - types-setuptools
          - types-reportlab
          - types-lxml
          - types-openpyxl
          - types-tabulate
        args: [
          "--python-version", "3.11",
          "--show-error-codes",
          "--pretty",
          "--ignore-missing-imports",
          "--allow-untyped-defs",
          "--allow-untyped-decorators",
          "--no-strict-optional",
        ]
        exclude: ^(tests/|docs/|examples/)

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
      - id: commitizen
        stages: [commit-msg] 