repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first
    - id: debug-statements
    - id: requirements-txt-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: uv run mypy
      language: system
      pass_filenames: false
      types: [python]
      require_serial: true
      args: ["-p", "nova", "--config-file=pyproject.toml", "--namespace-packages"]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.7
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: ["bandit[toml]"]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [--py310-plus]

- repo: local
  hooks:
    - id: docformatter
      name: docformatter
      description: 'Formats docstrings to follow PEP 257.'
      entry: docformatter
      language: python
      types: [python]
      args: [--in-place]
      additional_dependencies: ['docformatter==1.7.5']
