[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Nova Document Processor - Markdown Parse Phase"
authors = ["Your Name <your.email@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
markdown-it-py = ">=3.0.0,<4.0.0"
structlog = ">=24.1.0,<25.0.0"
python-dotenv = "^1.0.0"
markitdown = "0.0.1a3"
pydantic = ">=2.5.2,<3.0.0"
typer = "^0.9.0"
rich = "^13.7.0"
pyyaml = "^6.0.1"
pillow-heif = "^0.21.0"
pymupdf = "^1.25.1"
openai = "^1.14.0"
pyexiftool = "^0.5.5"
python-magic = "^0.4.27"

[tool.poetry.group.dev.dependencies]
black = ">=23.0.0,<24.0.0"
mypy = ">=1.0.0,<2.0.0"
pytest = ">=8.0.0,<9.0.0"
pytest-cov = ">=4.1.0,<5.0.0"
flake8 = ">=7.0.0,<8.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nova = "nova.cli.main:app"
