[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Nova Document Processor"
authors = ["Chad Walters"]

[tool.poetry.dependencies]
python = "^3.10"
markdown = "^3.5.1"
pdfkit = "^1.0.0"
aiofiles = "^23.2.0"
structlog = "^23.2.0"
PyPDF2 = "^3.0.1"
pikepdf = "^8.10.1"
PyMuPDF = "^1.23.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
