[tool.poetry]
name = "nova"
version = "0.1.0"
description = "A Python CLI tool for markdown file consolidation and PDF generation"
authors = ["Chad Walters"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
pillow = "^10.1.0"
pillow-heif = "^0.21.0"
markdown = "^3.5.1"
weasyprint = "57.1"
pydyf = "0.5.0"
jinja2 = "^3.1.2"
pyyaml = "^6.0.1"
structlog = "^23.2.0"
rich = "^13.7.0"
beautifulsoup4 = "^4.12.2"
pypdf = "^3.17.1"
tqdm = "^4.66.1"
typer = "^0.15.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"
black = "^23.11.0"
isort = "^5.12.0"
mypy = "^1.7.1"
pylint = "^3.0.2"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nova = "src.cli:app"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi-line-output = 3
line-length = 88

[tool.mypy]
python-version = "3.11"
warn-return-any = true
warn-unused-configs = true
disallow-untyped-defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"
filterwarnings = ["ignore::DeprecationWarning"]

[tool.coverage.run]
source = ["src"]
omit = ["tests/*", "**/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
    "pass",
    "raise ImportError",
]
  