[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Nova Document Processor"
authors = ["Your Name <your.email@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
markdown-it-py = ">=3.0.0,<4.0.0"
mdit-py-plugins = ">=0.4.0,<0.5.0"
weasyprint = ">=60.1,<61.0"
structlog = ">=24.1.0,<25.0.0"
python-dotenv = "^1.0.0"
markitdown = "0.0.1a3"
Pillow = "^10.0.0"
pydantic = ">=2.5.2,<3.0.0"
aiofiles = "^23.2.1"
typer = "^0.9.0"
rich = "^13.7.0"
psutil = "^5.9.6"
pyyaml = "^6.0.1"
pillow-heif = "^0.21.0"

[tool.poetry.group.dev.dependencies]
black = ">=23.0.0,<24.0.0"
mypy = ">=1.0.0,<2.0.0"
pytest = ">=8.0.0,<9.0.0"
pytest-asyncio = ">=0.23.5,<0.24.0"
pytest-cov = ">=4.1.0,<5.0.0"
flake8 = ">=7.0.0,<8.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nova = "nova.cli.main:app"
