[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Nova Document Processor"
authors = ["Chad Walters"]
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.0"
markdown = "^3.5.1"
aiofiles = "^23.2.0"
structlog = "^23.2.0"
PyMuPDF = "^1.23.8"
python-docx = "^0.8.11"
mammoth = "^1.6.0"
python-pptx = "^0.6.21"
python-dotenv = "^1.0.0"
rich = "^13.7.0"
jinja2 = "^3.1.3"
beautifulsoup4 = "^4.12.3"
python-magic = "^0.4.27"
psutil = "^5.9.8"
chardet = "^5.2.0"
weasyprint = "^52.5"
pydantic = "^2.6.1"
asyncio = "^3.4.3"
aiopath = "^0.6.11"
pyyaml = "^6.0.1"
pillow = "^10.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
