[project]
name = "nova"
version = "0.1.0"
description = "A RAG-based system for Bear.app notes with MCP integration"
authors = [
    {name = "Chad Walters", email = "chad@example.com"}
]
dependencies = [
    "pyyaml>=6.0.1",
    "anthropic>=0.3.11",
    "faiss-cpu>=1.7.4",
    "chromadb>=0.4.22",
    "docling==2.15.1",
    "docling-core[chunking]==2.14.0",
    "docling-ibm-models==3.1.2",
    "docling-parse==3.0.0",
    "sentence-transformers>=2.2.2"
]
requires-python = ">=3.10,<3.11"

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.25.0",
]
dev = [
    "mypy>=1.8.0",
    "types-PyYAML>=6.0.12.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
asyncio_mode = "auto"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[project.scripts]
nova = "nova.__main__:main"
