[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "nova"
version = "0.1.0"
description = "Nova MCP Server"
authors = [{ name = "Chad Walters", email = "chad@nova.ai" }]
dependencies = [
    "chromadb>=0.4.22",
    "sentence-transformers>=2.2.2",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.25.0",
    "pytest-benchmark>=4.0.0",
    "pytest-cov>=4.1.0",
    "pytest-timeout>=2.2.0",
    "pytest-xdist>=3.5.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = [
    "pytest>=7.4.4",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.23.5",
    "mypy>=1.8.0",
    "black>=23.12.1",
    "isort>=5.13.2",
    "flake8>=7.0.0",
    "types-requests>=2.31.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "strict"
timeout = 300

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = [
    "chromadb",
    "chromadb.api.types",
    "chromadb.config",
    "sentence_transformers",
    "aiohttp",
    "jsonschema.validators",
    "yaml",
]
ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[project.scripts]
nova = "nova.cli.main:main"

[tool.bandit]
exclude_dirs = ["tests"]
skips = [
    "B103",
    "B110",
] # Ignore file permission warnings and try-except-pass in error handlers
