[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Document processing pipeline"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.7.0"
markitdown = "0.0.1a3"
psutil = "^5.9.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-asyncio = "^0.23.3"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
