[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Nova - Personal Knowledge Management System with Claude Integration"
authors = ["Chad Walters"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
anthropic = "^0.42.0"
docling = "^2.15.1"
sentence-transformers = "^3.3.1"
faiss-cpu = "^1.9.0.post1"
pyyaml = "^6.0.2"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
mypy = "^1.14.1"
pre-commit = "^4.0.1"
black = "^24.10.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
