[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "nova"
version = "3.0.0"
description = "Nova document processing pipeline"
authors = ["Chad Walters <chad@bookedby.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "nova", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
aiofiles = "^23.2.1"
aiosqlite = "^0.19.0"
beautifulsoup4 = "^4.12.2"
click = "^8.1.7"
colorama = "^0.4.6"
docx2txt = "^0.8"
html2text = "^2020.1.16"
Jinja2 = "^3.1.2"
lxml = "^4.9.3"
Markdown = "^3.5.1"
numpy = "^1.26.2"
openpyxl = "^3.1.2"
pandas = "^2.1.4"
pdfminer-six = "^20221105"
Pillow = "^10.1.0"
python-pptx = "^0.6.22"
PyYAML = "^6.0.1"
rich = "^13.7.0"
tqdm = "^4.66.1"
python-docx = "^1.0.1"
pypdf2 = "^3.0.1"
pypandoc = "^1.12"
pydantic = "^2.6.1"
openai = "^1.12.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pytest-mock = "^3.14.0"
pytest-timeout = "^2.3.1"
pytest-asyncio = "^0.25.0"

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
