[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Nova Document Processor"
authors = ["Your Name <your.email@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
markdown-it-py = "^3.0.0"
mdit-py-plugins = "^0.4.0"
weasyprint = "^60.1"
structlog = "^24.1.0"
python-dotenv = "^1.0.0"
markitdown = {git = "https://github.com/microsoft/markitdown.git"}
python-docx = "^1.0.0"
PyMuPDF = "^1.23.8"
python-pptx = "^0.6.21"
Pillow = "^10.2.0"
pydantic = "^2.5.3"
jsonschema = "^4.21.1"
aiofiles = "^23.2.1"
aiohttp = "^3.9.1"
typer = "^0.9.0"
rich = "^13.7.0"

[tool.poetry.group.dev.dependencies]
black = "^23.0.0"
mypy = "^1.0.0"
pytest = "^8.0.0"
pytest-asyncio = "^0.23.5"
pytest-cov = "^4.1.0"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nova = "nova.cli.main:app"
