[tool.poetry]
name = "nova"
version = "0.1.0"
description = "Nova Document Processor"
authors = ["Chad Walters"]

[tool.poetry.dependencies]
python = "^3.12"
markitdown = "^0.0.1a3"
chardet = "^5.2.0"
python-magic = "^0.4.27"
Pillow = "^10.1.0"
rich = "^13.9.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
