# Default configuration for Nova document processing system

base_dir: ~/nova
input_dir: ${base_dir}/_NovaInput
output_dir: ${base_dir}/_Nova
processing_dir: ${base_dir}/_NovaProcessing

cache:
  dir: ${base_dir}/_NovaCache
  enabled: true
  ttl: 3600  # 1 hour default TTL

apis:
  openai:
    api_key: ""  # Set this in your user config file
    model: "gpt-4o"  # Vision-capable model
    max_tokens: 500
    vision_prompt: |
      Please analyze this image and provide a detailed description.
      If it's a screenshot, extract any visible text.
      If it's a photograph, describe the scene and key elements.
      Focus on what makes this image relevant in a note-taking context.

# Handler Configuration
handlers:
  image:
    formats:
      - jpg
      - jpeg
      - png
      - gif
      - webp
      - heic
      - svg

# Pipeline Configuration
pipeline:
  phases:
    - parse
    - disassemble
    - split
    - finalize

logging:
  level: INFO  # Default to INFO if not set
  file_level: DEBUG
  console_level: INFO
  log_dir: ${base_dir}/_NovaLogs
  format: "%(asctime)s [%(levelname)s] %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  handlers: ["console", "file"]
  phase_levels:
    parse: INFO
    disassemble: INFO
    split: INFO
    finalize: INFO
  handler_levels:
    document: INFO
    image: INFO
    markdown: INFO
    text: INFO
    spreadsheet: INFO
    html: INFO
  structured: true
  include_context: true

# Debug Configuration
debug:
  enabled: false  # Can be enabled via environment variable
  phase_flags:  # Enable debug for specific phases
    parse: false 