# Nova Document Processor Configuration

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  filter_binary: true
  max_binary_length: 100

# Markdown Processing
markdown:
  typographer: true
  linkify: true
  breaks: true
  plugins:
    - table
    - strikethrough
    - taskList
    - linkify
    - image

# Image Processing
image:
  quality: 85
  max_width: 1920
  max_height: 1080
  preferred_format: "png"
  cache_enabled: true
  cache_duration: 86400  # 24 hours
  retry_attempts: 3
  timeout: 30

# Office Document Processing
office:
  preserve_images: true
  ocr_enabled: true
  max_image_size: 5242880  # 5MB

# Processing Configuration
processing:
  error_tolerance: "lenient"
  max_retries: 3
  max_file_size: 100  # MB
  max_total_size: 500  # MB