# Nova Document Processor Configuration
# First Phase: Markdown Parse

processing:
  error_tolerance: lenient
  max_retries: 3
  max_file_size: 100  # MB
  max_total_size: 500  # MB

logging:
  level: INFO
  format: json
  filter_binary: true
  max_binary_length: 100

markdown:
  typographer: true
  linkify: true
  breaks: true
  plugins:
    - table
    - strikethrough
    - taskList
    - linkify
    - image