style:
  page_size: 'A4'
  margin: '0.5in'
  font_family: 'Arial'
  font_size: '11pt'
  line_height: '1.5'
  colors:
    text: '#333333'
    headings: '#000000'
    links: '#0066cc'
  pdf:
    optimize: true
    zoom: 1.0
header:
  enabled: false
  content: ''
  page_numbers: false
footer:
  enabled: false
  content: ''
  page_numbers: false
