# Nova Document Processor Configuration

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "INFO"
      formatter: "default"
  use_rich: true

# OpenAI Configuration
openai:
  enabled: true
  model: "gpt-4-0125-preview"
  max_tokens: 500
  temperature: 0.7
  retry:
    max_retries: 3
    delay_between_retries: 1.0
    backoff_factor: 2.0
    jitter: true
    retry_on_errors:
      - timeout
      - connection_error

# Global Retry Configuration
retry:
  max_retries: 3
  delay_between_retries: 1.0
  backoff_factor: 2.0
  jitter: true
  retry_on_errors:
    - timeout
    - connection_error

# Global Cache Configuration
cache:
  enabled: true
  max_size: 1073741824  # 1GB
  max_age: 2592000      # 30 days
  cleanup_interval: 3600 # 1 hour