# Nova Configuration

# Base Directories
base_dir: "${HOME}/Library/Mobile Documents/com~apple~CloudDocs"
input_dir: "${HOME}/Library/Mobile Documents/com~apple~CloudDocs/_NovaInput"
output_dir: "${HOME}/Library/Mobile Documents/com~apple~CloudDocs/_Nova"
processing_dir: "${HOME}/Library/Mobile Documents/com~apple~CloudDocs/_NovaProcessing"

# Cache Configuration
cache:
  dir: "${HOME}/Library/Mobile Documents/com~apple~CloudDocs/_NovaCache"
  enabled: true
  ttl: 3600  # 1 hour

# API Configuration
apis:
  openai:
    api_key: ${OPENAI_API_KEY}
    model: "gpt-4o"
    max_tokens: 500
    vision_prompt: |
      Please analyze this image and provide a detailed description.
      If it's a screenshot, extract any visible text.
      If it's a photograph, describe the scene and key elements.
      Focus on what makes this image relevant in a note-taking context.

# Handler Configuration
handlers:
  image:
    formats:
      - jpg
      - jpeg
      - png
      - gif
      - webp
      - heic
      - svg

# Logging Configuration
# Can be overridden by NOVA_LOG_LEVEL environment variable
# Levels: ERROR, WARNING, INFO, DEBUG
logging:
  level: "ERROR"
  file: "nova.log" 

# Pipeline Configuration
pipeline:
  phases:
    - parse
    - split
    - finalize 