# Nova Configuration Template
# Copy this file to nova.yaml and update the values

# Base Directories
base_dir: "~/Documents/Nova"
input_dir: "~/Documents/Nova/Input"
output_dir: "~/Documents/Nova/Output"

# Cache Configuration
cache:
  dir: "~/Documents/Nova/Cache"
  enabled: true
  ttl: 3600  # 1 hour

# API Configuration
apis:
  openai:
    api_key: "your-api-key-here"
    model: "gpt-4o"
    max_tokens: 500
    vision_prompt: |
      Please analyze this image and provide a detailed description.
      If it's a screenshot, extract any visible text.
      If it's a photograph, describe the scene and key elements.
      Focus on what makes this image relevant in a note-taking context.

# Handler Configuration
handlers:
  image:
    formats:
      - jpg
      - jpeg
      - png
      - gif
      - webp
      - heic
      - svg

# Logging Configuration
logging:
  level: "INFO"
  file: "nova.log" 