# Nova Configuration Template
# Copy this file to nova.yaml and update the values

# Base Directories
base_dir: "${HOME}/Documents/Nova"
input_dir: "${HOME}/Documents/Nova/Input"
output_dir: "${HOME}/Documents/Nova/Output"
processing_dir: "${HOME}/Documents/Nova/Processing"

# Cache Configuration
cache:
  dir: "${HOME}/Documents/Nova/Cache"
  enabled: true
  ttl: 3600  # 1 hour

# API Configuration
apis:
  openai:
    api_key: ${OPENAI_API_KEY}
    model: "gpt-4o"
    max_tokens: 500
    vision_prompt: |
      Please analyze this image and provide a detailed description.
      If it's a screenshot, extract any visible text.
      If it's a photograph, describe the scene and key elements.
      Focus on what makes this image relevant in a note-taking context.

# Handler Configuration
handlers:
  image:
    formats:
      - jpg
      - jpeg
      - png
      - gif
      - webp
      - heic
      - svg

# Pipeline Configuration
pipeline:
  phases:
    - parse
    - disassemble
    - split
    - finalize 