# Nova Configuration Template
# Only override what's specific to your setup

# Base directory for all Nova files
base_dir: ~/nova

# API keys (sensitive information)
apis:
  openai:
    api_key: "your-api-key-here"  # Replace with your actual API key 