pipeline:
  paths:
    base_dir: "${NOVA_BASE_DIR}"
  components:
    markdown_processor:
      parser: "markitdown==0.0.1a3"
      config:
        document_conversion: true
        image_processing: true
        metadata_preservation: true
    image_processor:
      formats:
        - png
        - jpg/jpeg
        - gif
        - webp
        - heic/HEIC
      operations:
        - format_conversion:
            heic_to_jpg: true
            optimize_quality: 85
        - size_optimization:
            preserve_aspect_ratio: true
            max_dimensions: [1920, 1080]
        - metadata:
            extract: true
            preserve_original: true
        - description_generation:
            use_openai: true
            model: "gpt-4-vision-preview"
            cache_results: true
    office_processor:
      formats:
        - docx/doc:
            extract_text: true
            preserve_paragraphs: true
        - pptx/ppt:
            extract_slides: true
            include_notes: true
        - xlsx/xls:
            table_format: true
            preserve_headers: true
        - pdf:
            extract_text: true
            preserve_layout: true
        - csv:
            detect_encoding: true
            table_format: true
      operations:
        - text_extraction:
            preserve_formatting: true
            handle_unicode: true
        - image_extraction:
            process_embedded: true
            maintain_links: true
        - metadata:
            preserve_all: true
            track_changes: true
  phases:
    - MARKDOWN_PARSE:
        description: "Parse and process markdown files with embedded content"
        output_dir: "${NOVA_PHASE_MARKDOWN_PARSE}"
        processor: "MarkdownProcessor"
        enabled: true
        handlers:
          - type: "UnifiedHandler"
            base_handler: "nova.phases.core.base_handler.BaseHandler"
            options:
              document_conversion: true
              image_processing: true
              metadata_preservation: true
              sort_by_date: true
              preserve_headers: true
              section_markers:
                start: "<!-- START_FILE: {filename} -->"
                end: "<!-- END_FILE: {filename} -->"
                separator: "\n---\n"
    
    - MARKDOWN_CONSOLIDATE:
        description: "Consolidate markdown files with their attachments"
        output_dir: "${NOVA_PHASE_MARKDOWN_CONSOLIDATE}"
        processor: "MarkdownConsolidateProcessor"
        enabled: true
        handlers:
          - type: "UnifiedHandler"
            base_handler: "nova.phases.core.base_handler.BaseHandler"
            options:
              copy_attachments: true
              update_references: true
              merge_content: true
              preserve_headers: true
              sort_by_date: true
    
    - MARKDOWN_AGGREGATE:
        description: "Aggregate all consolidated markdown files into a single file"
        output_dir: "${NOVA_PHASE_MARKDOWN_AGGREGATE}"
        processor: "MarkdownAggregateProcessor"
        enabled: true
        handlers:
          - type: "UnifiedHandler"
            base_handler: "nova.phases.core.base_handler.BaseHandler"
            options:
              section_markers:
                start: "<!-- START_FILE: {filename} -->"
                end: "<!-- END_FILE: {filename} -->"
                separator: "\n---\n"
              sort_by_date: true
              preserve_headers: true
              add_navigation: true
              link_style: "text"
              templates:
                text:
                  prev: "← Previous: [{title}]({link})"
                  next: "Next: [{title}]({link}) →"
                  top: "[↑ Back to Top](#table-of-contents)"
    
    - MARKDOWN_SPLIT:
        description: "Split aggregated markdown into separate files for summary, raw notes, and attachments"
        output_dir: "${NOVA_PHASE_MARKDOWN_SPLIT}"
        processor: "ThreeFileSplitProcessor"
        enabled: true
        handlers:
          - type: "UnifiedHandler"
            base_handler: "nova.phases.core.base_handler.BaseHandler"
            options:
              output_files:
                summary: "summary.md"
                raw_notes: "raw_notes.md"
                attachments: "attachments.md"
              section_markers:
                summary: "--==SUMMARY==--"
                raw_notes: "--==RAW_NOTES==--"
                attachments: "--==ATTACHMENTS==--"
              content_type_rules:
                summary:
                  - Contains high-level overviews
                  - Contains key insights and decisions
                  - Contains structured content
                raw_notes:
                  - Contains detailed notes and logs
                  - Contains chronological entries
                  - Contains unstructured content
                attachments:
                  - Contains file references
                  - Contains embedded content
                  - Contains metadata 