# Nova Document Processor Pipeline Configuration

pipeline:
  cache:
    enabled: true
    directory: "/Users/ChadWalters/Library/Mobile Documents/com~apple~CloudDocs/_NovaProcessing/.state"
    max_size_mb: 1024
    max_age_days: 7
    cleanup_on_start: true
    cleanup_on_error: true

  phases:
    MARKDOWN_PARSE:
      name: "markdown_parse"
      description: "Parse and process markdown files with embedded content"
      input_dir: "/Users/ChadWalters/Library/Mobile Documents/com~apple~CloudDocs/_NovaInput"
      output_dir: "/Users/ChadWalters/Library/Mobile Documents/com~apple~CloudDocs/_NovaProcessing/phases/markdown_parse"
      processor: "MarkdownParseProcessor"
      components:
        markdown_processor:
          parser: "markitdown==0.0.1a3"
          config:
            document_conversion: true
            image_processing: true
            metadata_preservation: true
          handlers:
            - MarkdownHandler:
                config:
                  document_conversion: true
                  image_processing: true
                  metadata_preservation: true
            - ConsolidationHandler:
                config:
                  sort_by_date: true
                  preserve_headers: true 